apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - cp4ba-argo-role.yaml
  - cp4ba-argo-rb.yaml

  #- secrets-generator.yaml
  - common.yaml
  - kibana-operator.yaml
  - operator.yaml
  - operand.yaml
